import type { Metadata } from "next";
import { Tajawal } from "next/font/google";
import "./globals.css";

// إعداد خط Tajawal
const tajawal = Tajawal({
  subsets: ["arabic", "latin"], // دعم الحروف العربية واللاتينية
  weight: ["200", "300", "400", "500", "700", "800", "900"], // يمكنك ترك الأوزان التي تحتاجها فقط لتسريع التحميل
  variable: "--font-tajawal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ar" // تغيير اللغة إلى العربية
      dir="rtl" // إضافة اتجاه النص من اليمين لليسار
      className={`${tajawal.variable} h-full antialiased`}
    >
      {/* استخدمنا المتغير هنا، أو يمكنك إضافة font-sans إذا قمت بإعداده في Tailwind */}
      <body className={`min-h-full flex flex-col font-sans`}>{children}</body>
    </html>
  );
}