import type { Metadata } from "next";
import { Tajawal } from "next/font/google";
import "./globals.css";

const tajawal = Tajawal({
  subsets: ["arabic", "latin"],
  weight: ["400", "500", "700"], // حسب الحاجة
});

export const metadata: Metadata = {
  title: "جمعية نهضة العكنة الخيرية",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar">
      <body className={`${tajawal.className} antialiased min-h-full flex flex-col`}>
        {children}
      </body>
    </html>
  );
}